services:
  - type: web
    name: healthwatch-website
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /sitemap.xml
        name: Cache-Control
        value: public, max-age=86400
